[project]
name = "weather-assistant"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "chainlit>=2.6.2",
    "dotenv>=0.9.9",
    "httpx>=0.28.1",
    "openai-agents>=0.2.3",
    "requests>=2.32.4",
]
